      - name: Run Cypress tests
        run: npx cypress run --browser chrome --config-file cypress.config.js --spec "cypress/e2e/**/*.cy.js"

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
